apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gargi-app-1
  namespace: default
spec:
  interval: 15m
  path: "./gitops-flux/repositories/gargi-app-1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gargi-app-1
